# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4026b075188af4275fca52380c0f5ad4213442e228c0c232c3428ce22da48b406c3afe2c863fc98975c70bf39571a640bbf5a9fd71a91646c1b68332cecd6e5

test:
  secret_key_base: 7300ec6615dfa1f63c2375c37122c763876f29f42b80f632ecf5882b6bab8b99b05a85aba7adbb24bd2fee9845ca9bb77fbbb35b1bf123841aaf7d31a67f4707

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
